### PR TITLE
Updated README.md & Release.md

### PR DESCRIPTION
**Pull request by arichornlover**
I updated this to improve spelling & workarounds for broken tweaks, hope this helps!

### CODE REVIEW

**Comment by Balackburn** [comment]
@arichorn Thank you

**Comment by arichornlover** [comment]
No problem! the changes just seemed important 👍

**Comment by arichornlover** [comment]
And Balackburn, I made a forked version of YTReExplore called YTReNotifications was wondering if you wanted to try it out, it’s inspired off of a feature that was from YouTube Revanced. And I will test it later to see if it works. Anyways enjoy!
```
// YTReNotifications: https://github.com/PoomSmart/YTReExplore (forked by @arichorn)
%group gReNotifications
static void replaceNotificationsTab(YTIGuideResponse *response) {
    NSMutableArray<YTIGuideResponseSupportedRenderers *> *renderers = [response itemsArray];
    for (YTIGuideResponseSupportedRenderers *guideRenderers in renderers) {
        YTIPivotBarRenderer *pivotBarRenderer = [guideRenderers pivotBarRenderer];
        NSMutableArray<YTIPivotBarSupportedRenderers *> *items = [pivotBarRenderer itemsArray];
        NSUInteger createIndex = [items indexOfObjectPassingTest:^BOOL(YTIPivotBarSupportedRenderers *renderers, NSUInteger idx, BOOL *stop) {
            return [[[renderers pivotBarItemRenderer] pivotIdentifier] isEqualToString:@"FEuploads"];
        }];
        NSUInteger notificationsIndex = [items indexOfObjectPassingTest:^BOOL(YTIPivotBarSupportedRenderers *renderers, NSUInteger idx, BOOL *stop) {
            return [[[renderers pivotBarItemRenderer] pivotIdentifier] isEqualToString:@"FEnotifications"];
        }];
        NSUInteger subscriptionsIndex = [items indexOfObjectPassingTest:^BOOL(YTIPivotBarSupportedRenderers *renderers, NSUInteger idx, BOOL *stop) {
            return [[[renderers pivotBarItemRenderer] pivotIdentifier] isEqualToString:@"FEsubscriptions"];
        }];
        if (createIndex != NSNotFound && notificationsIndex != NSNotFound && subscriptionsIndex != NSNotFound) {
            [items removeObjectAtIndex:createIndex];
            [items removeObjectAtIndex:notificationsIndex];
            YTIPivotBarSupportedRenderers *notificationsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEnotifications" title:@"Notifications" iconType:62];
            [items insertObject:notificationsTab atIndex:createIndex];
            NSInteger subscriptionsInsertIndex = (items.count % 2 == 0) ? items.count / 2 : (items.count + 1) / 2;
            YTIPivotBarSupportedRenderers *subscriptionsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEsubscriptions" title:@"Subscriptions" iconType:24];
            [items insertObject:subscriptionsTab atIndex:subscriptionsInsertIndex];
        } else {
            NSUInteger notificationsPosition = MAX(notificationsIndex, subscriptionsIndex) + 1;
            if (notificationsPosition != NSNotFound) {
                YTIPivotBarSupportedRenderers *notificationsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEnotifications" title:@"Notifications" iconType:62];
                [items insertObject:notificationsTab atIndex:notificationsPosition];
            } else {
                YTIPivotBarSupportedRenderers *notificationsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEnotifications" title:@"Notifications" iconType:62];
                [items addObject:notificationsTab];
            }
        }
    }
}
%hook YTGuideServiceCoordinator
- (void)handleResponse:(YTIGuideResponse *)response withCompletion:(id)completion {
    replaceNotificationsTab(response);
    %orig(response, completion);
}
- (void)handleResponse:(YTIGuideResponse *)response error:(id)error completion:(id)completion {
    replaceNotificationsTab(response);
    %orig(response, error, completion);
}
%end
%end
```

**Comment by Balackburn** [comment]
@arichorn Thank you, what does it do exactly? Obviously I will add it to YTLitePlus and CercubePlusExtra if it work correctly keep me updated thx.

**Comment by arichornlover** [comment]
> @arichorn Thank you, what does it do exactly? Obviously I will add it to YTLitePlus and CercubePlusExtra if it work correctly keep me updated thx.

Here’s what it’s supposed to do
it’s supposed to re-add the “Notifications” Tab in the pivot bar. and then remove the “Create(+)” Tab and then reposition the “Subscriptions” tab to the center. 

This image was from google to show an example
IMG_2245

**Comment by Balackburn** [comment]
@arichorn I remember this tab, but I never realized it had been removed, as the application changes so much over time without me realizing it.

**Comment by arichornlover** [comment]
> @arichorn I remember this tab, but I never realized it had been removed, as the application changes so much over time without me realizing it.

it’s either been disabled or removed in the app for 2+ years, so today I just recently decided to try to add it back.

**Comment by arichornlover** [comment]
> And Balackburn, I made a forked version of YTReExplore called YTReNotifications was wondering if you wanted to try it out, it’s inspired off of a feature that was from YouTube Revanced. And I will test it later to see if it works. Anyways enjoy!
> 
> ```
> // YTReNotifications: https://github.com/PoomSmart/YTReExplore (forked by @arichorn)
> %group gReNotifications
> static void replaceNotificationsTab(YTIGuideResponse *response) {
>     NSMutableArray<YTIGuideResponseSupportedRenderers *> *renderers = [response itemsArray];
>     for (YTIGuideResponseSupportedRenderers *guideRenderers in renderers) {
>         YTIPivotBarRenderer *pivotBarRenderer = [guideRenderers pivotBarRenderer];
>         NSMutableArray<YTIPivotBarSupportedRenderers *> *items = [pivotBarRenderer itemsArray];
>         NSUInteger createIndex = [items indexOfObjectPassingTest:^BOOL(YTIPivotBarSupportedRenderers *renderers, NSUInteger idx, BOOL *stop) {
>             return [[[renderers pivotBarItemRenderer] pivotIdentifier] isEqualToString:@"FEuploads"];
>         }];
>         NSUInteger notificationsIndex = [items indexOfObjectPassingTest:^BOOL(YTIPivotBarSupportedRenderers *renderers, NSUInteger idx, BOOL *stop) {
>             return [[[renderers pivotBarItemRenderer] pivotIdentifier] isEqualToString:@"FEnotifications"];
>         }];
>         NSUInteger subscriptionsIndex = [items indexOfObjectPassingTest:^BOOL(YTIPivotBarSupportedRenderers *renderers, NSUInteger idx, BOOL *stop) {
>             return [[[renderers pivotBarItemRenderer] pivotIdentifier] isEqualToString:@"FEsubscriptions"];
>         }];
>         if (createIndex != NSNotFound && notificationsIndex != NSNotFound && subscriptionsIndex != NSNotFound) {
>             [items removeObjectAtIndex:createIndex];
>             [items removeObjectAtIndex:notificationsIndex];
>             YTIPivotBarSupportedRenderers *notificationsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEnotifications" title:@"Notifications" iconType:62];
>             [items insertObject:notificationsTab atIndex:createIndex];
>             NSInteger subscriptionsInsertIndex = (items.count % 2 == 0) ? items.count / 2 : (items.count + 1) / 2;
>             YTIPivotBarSupportedRenderers *subscriptionsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEsubscriptions" title:@"Subscriptions" iconType:24];
>             [items insertObject:subscriptionsTab atIndex:subscriptionsInsertIndex];
>         } else {
>             NSUInteger notificationsPosition = MAX(notificationsIndex, subscriptionsIndex) + 1;
>             if (notificationsPosition != NSNotFound) {
>                 YTIPivotBarSupportedRenderers *notificationsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEnotifications" title:@"Notifications" iconType:62];
>                 [items insertObject:notificationsTab atIndex:notificationsPosition];
>             } else {
>                 YTIPivotBarSupportedRenderers *notificationsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEnotifications" title:@"Notifications" iconType:62];
>                 [items addObject:notificationsTab];
>             }
>         }
>     }
> }
> %hook YTGuideServiceCoordinator
> - (void)handleResponse:(YTIGuideResponse *)response withCompletion:(id)completion {
>     replaceNotificationsTab(response);
>     %orig(response, completion);
> }
> - (void)handleResponse:(YTIGuideResponse *)response error:(id)error completion:(id)completion {
>     replaceNotificationsTab(response);
>     %orig(response, error, completion);
> }
> %end
> %end
> ```

this will crash the app, because I recently just tested it multiple times. and I'm so sorry that this code isn't working as I expected it would.

**Comment by Balackburn** [comment]
> > And Balackburn, I made a forked version of YTReExplore called YTReNotifications was wondering if you wanted to try it out, it’s inspired off of a feature that was from YouTube Revanced. And I will test it later to see if it works. Anyways enjoy!
> > ```
> > // YTReNotifications: https://github.com/PoomSmart/YTReExplore (forked by @arichorn)
> > %group gReNotifications
> > static void replaceNotificationsTab(YTIGuideResponse *response) {
> >     NSMutableArray<YTIGuideResponseSupportedRenderers *> *renderers = [response itemsArray];
> >     for (YTIGuideResponseSupportedRenderers *guideRenderers in renderers) {
> >         YTIPivotBarRenderer *pivotBarRenderer = [guideRenderers pivotBarRenderer];
> >         NSMutableArray<YTIPivotBarSupportedRenderers *> *items = [pivotBarRenderer itemsArray];
> >         NSUInteger createIndex = [items indexOfObjectPassingTest:^BOOL(YTIPivotBarSupportedRenderers *renderers, NSUInteger idx, BOOL *stop) {
> >             return [[[renderers pivotBarItemRenderer] pivotIdentifier] isEqualToString:@"FEuploads"];
> >         }];
> >         NSUInteger notificationsIndex = [items indexOfObjectPassingTest:^BOOL(YTIPivotBarSupportedRenderers *renderers, NSUInteger idx, BOOL *stop) {
> >             return [[[renderers pivotBarItemRenderer] pivotIdentifier] isEqualToString:@"FEnotifications"];
> >         }];
> >         NSUInteger subscriptionsIndex = [items indexOfObjectPassingTest:^BOOL(YTIPivotBarSupportedRenderers *renderers, NSUInteger idx, BOOL *stop) {
> >             return [[[renderers pivotBarItemRenderer] pivotIdentifier] isEqualToString:@"FEsubscriptions"];
> >         }];
> >         if (createIndex != NSNotFound && notificationsIndex != NSNotFound && subscriptionsIndex != NSNotFound) {
> >             [items removeObjectAtIndex:createIndex];
> >             [items removeObjectAtIndex:notificationsIndex];
> >             YTIPivotBarSupportedRenderers *notificationsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEnotifications" title:@"Notifications" iconType:62];
> >             [items insertObject:notificationsTab atIndex:createIndex];
> >             NSInteger subscriptionsInsertIndex = (items.count % 2 == 0) ? items.count / 2 : (items.count + 1) / 2;
> >             YTIPivotBarSupportedRenderers *subscriptionsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEsubscriptions" title:@"Subscriptions" iconType:24];
> >             [items insertObject:subscriptionsTab atIndex:subscriptionsInsertIndex];
> >         } else {
> >             NSUInteger notificationsPosition = MAX(notificationsIndex, subscriptionsIndex) + 1;
> >             if (notificationsPosition != NSNotFound) {
> >                 YTIPivotBarSupportedRenderers *notificationsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEnotifications" title:@"Notifications" iconType:62];
> >                 [items insertObject:notificationsTab atIndex:notificationsPosition];
> >             } else {
> >                 YTIPivotBarSupportedRenderers *notificationsTab = [%c(YTIPivotBarRenderer) pivotSupportedRenderersWithBrowseId:@"FEnotifications" title:@"Notifications" iconType:62];
> >                 [items addObject:notificationsTab];
> >             }
> >         }
> >     }
> > }
> > %hook YTGuideServiceCoordinator
> > - (void)handleResponse:(YTIGuideResponse *)response withCompletion:(id)completion {
> >     replaceNotificationsTab(response);
> >     %orig(response, completion);
> > }
> > - (void)handleResponse:(YTIGuideResponse *)response error:(id)error completion:(id)completion {
> >     replaceNotificationsTab(response);
> >     %orig(response, error, completion);
> > }
> > %end
> > %end
> > ```
> 
> this will crash the app, because I recently just tested it multiple times. and I'm so sorry that this code isn't working as I expected it would.

Don't be sorry for that no problem.

**Pull request merged**
